services:
  - type: web
    name: personal-data-leak-checker
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn --chdir server app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///server/app.db
